<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'rapture\\propel\\behavior\\blameabletrait' => '/../src/Behavior/BlameableTrait.php',
                'rapture\\propel\\behavior\\sluggabletrait' => '/../src/Behavior/SluggableTrait.php',
                'rapture\\propel\\behavior\\softdeletetrait' => '/../src/Behavior/SoftDeleteTrait.php',
                'rapture\\propel\\behavior\\timestamptrait' => '/../src/Behavior/TimestampTrait.php',
                'rapture\\propel\\schema' => '/../src/Schema.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
